### ISSUE TITLE
wildcard match nested paths

### ISSUE THREAD

**Issue by thos37** [DomKM/silk#22]
I'm attempting to match the whole tree under a root path.  I tried the following, but it only matches a wildcard on one level, but returns nil on anything deeper:
```
[:css [["css" (silk/regex :uri #"(.*)")]]]
```
That matches "/css/this.css" but not "/css/deeper/that.css"  I'm not seeing any mention of this in the readme or the docs?

Also this always returns nil:
```
[:css [[(silk/regex :uri #"css(.*)")]]]
```

**Comment by thos37** [comment]
I guess this is by design and assumes that nested asset paths will be handled by another ring handler?

**Comment by DomKM** [comment]
Hi @thos37,

Yeah, I would handle this with a different handler. For assets, I'd suggest something like [Optimus](https://github.com/magnars/optimus).

Cheers,
Dom
