### ISSUE TITLE
Cljx dependancy is leaking to user project

### ISSUE THREAD

**Issue by Deraen** [DomKM/silk#9]
Cljx plugin should probably be defined on :dev profile to prevent it being added to project dependencies.

https://github.com/lynaghk/cljx#installation

**Comment by DomKM** [comment]
Thanks for the notification. I wonder why the other plugins aren't also dependencies.

**Comment by Deraen** [comment]
It's not the plugin directly but what the plugin does.

Cljx 0.4.0 adds the cljx dependency to the project and thus pom will contain dependency to it.
0.5.0 has some code to make sure the dependency is only added when running repl, but using :dev profile might still be a good idea.

https://github.com/lynaghk/cljx/blob/master/src/cljx/plugin.clj#L27

**Comment by DomKM** [comment]
Thanks for the notification and explanation.
